// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: translate-application/translate.proto
// Protobuf Java Version: 4.26.0

package com.github.paopaoyue.mesh.translate_application.proto;

public final class Translate {
  private Translate() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      Translate.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code rpc.ServiceStatusCode}
   */
  public enum ServiceStatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVICE_OK = 0;</code>
     */
    SERVICE_OK(0),
    /**
     * <code>LOCALE_NOT_SUPPORTED = 110002;</code>
     */
    LOCALE_NOT_SUPPORTED(110002),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        ServiceStatusCode.class.getName());
    }
    /**
     * <code>SERVICE_OK = 0;</code>
     */
    public static final int SERVICE_OK_VALUE = 0;
    /**
     * <code>LOCALE_NOT_SUPPORTED = 110002;</code>
     */
    public static final int LOCALE_NOT_SUPPORTED_VALUE = 110002;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServiceStatusCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServiceStatusCode forNumber(int value) {
      switch (value) {
        case 0: return SERVICE_OK;
        case 110002: return LOCALE_NOT_SUPPORTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceStatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServiceStatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceStatusCode>() {
            public ServiceStatusCode findValueByNumber(int number) {
              return ServiceStatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.paopaoyue.mesh.translate_application.proto.Translate.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServiceStatusCode[] VALUES = values();

    public static ServiceStatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServiceStatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rpc.ServiceStatusCode)
  }

  public interface TranslateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.TranslateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>string locale = 2;</code>
     * @return The locale.
     */
    java.lang.String getLocale();
    /**
     * <code>string locale = 2;</code>
     * @return The bytes for locale.
     */
    com.google.protobuf.ByteString
        getLocaleBytes();
  }
  /**
   * Protobuf type {@code rpc.TranslateRequest}
   */
  public static final class TranslateRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.TranslateRequest)
      TranslateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        TranslateRequest.class.getName());
    }
    // Use TranslateRequest.newBuilder() to construct.
    private TranslateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TranslateRequest() {
      text_ = "";
      locale_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest.class, com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object locale_ = "";
    /**
     * <code>string locale = 2;</code>
     * @return The locale.
     */
    @java.lang.Override
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      }
    }
    /**
     * <code>string locale = 2;</code>
     * @return The bytes for locale.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(locale_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, locale_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(locale_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, locale_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest)) {
        return super.equals(obj);
      }
      com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest other = (com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (!getLocale()
          .equals(other.getLocale())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + LOCALE_FIELD_NUMBER;
      hash = (53 * hash) + getLocale().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.TranslateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.TranslateRequest)
        com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest.class, com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest.Builder.class);
      }

      // Construct using com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ = "";
        locale_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateRequest_descriptor;
      }

      @java.lang.Override
      public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest getDefaultInstanceForType() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest build() {
        com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest buildPartial() {
        com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest result = new com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.text_ = text_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.locale_ = locale_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest) {
          return mergeFrom((com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest other) {
        if (other == com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLocale().isEmpty()) {
          locale_ = other.locale_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                locale_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object locale_ = "";
      /**
       * <code>string locale = 2;</code>
       * @return The locale.
       */
      public java.lang.String getLocale() {
        java.lang.Object ref = locale_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          locale_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string locale = 2;</code>
       * @return The bytes for locale.
       */
      public com.google.protobuf.ByteString
          getLocaleBytes() {
        java.lang.Object ref = locale_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locale_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string locale = 2;</code>
       * @param value The locale to set.
       * @return This builder for chaining.
       */
      public Builder setLocale(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        locale_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string locale = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocale() {
        locale_ = getDefaultInstance().getLocale();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string locale = 2;</code>
       * @param value The bytes for locale to set.
       * @return This builder for chaining.
       */
      public Builder setLocaleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        locale_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rpc.TranslateRequest)
    }

    // @@protoc_insertion_point(class_scope:rpc.TranslateRequest)
    private static final com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest();
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TranslateRequest>
        PARSER = new com.google.protobuf.AbstractParser<TranslateRequest>() {
      @java.lang.Override
      public TranslateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TranslateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TranslateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TranslateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.TranslateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>string locale = 2;</code>
     * @return The locale.
     */
    java.lang.String getLocale();
    /**
     * <code>string locale = 2;</code>
     * @return The bytes for locale.
     */
    com.google.protobuf.ByteString
        getLocaleBytes();

    /**
     * <code>string result = 3;</code>
     * @return The result.
     */
    java.lang.String getResult();
    /**
     * <code>string result = 3;</code>
     * @return The bytes for result.
     */
    com.google.protobuf.ByteString
        getResultBytes();

    /**
     * <code>.rpc.RespBase base = 255;</code>
     * @return Whether the base field is set.
     */
    boolean hasBase();
    /**
     * <code>.rpc.RespBase base = 255;</code>
     * @return The base.
     */
    com.github.paopaoyue.mesh.rpc.proto.Base.RespBase getBase();
    /**
     * <code>.rpc.RespBase base = 255;</code>
     */
    com.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder getBaseOrBuilder();
  }
  /**
   * Protobuf type {@code rpc.TranslateResponse}
   */
  public static final class TranslateResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.TranslateResponse)
      TranslateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        TranslateResponse.class.getName());
    }
    // Use TranslateResponse.newBuilder() to construct.
    private TranslateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TranslateResponse() {
      text_ = "";
      locale_ = "";
      result_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse.class, com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object locale_ = "";
    /**
     * <code>string locale = 2;</code>
     * @return The locale.
     */
    @java.lang.Override
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      }
    }
    /**
     * <code>string locale = 2;</code>
     * @return The bytes for locale.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object result_ = "";
    /**
     * <code>string result = 3;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string result = 3;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASE_FIELD_NUMBER = 255;
    private com.github.paopaoyue.mesh.rpc.proto.Base.RespBase base_;
    /**
     * <code>.rpc.RespBase base = 255;</code>
     * @return Whether the base field is set.
     */
    @java.lang.Override
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.rpc.RespBase base = 255;</code>
     * @return The base.
     */
    @java.lang.Override
    public com.github.paopaoyue.mesh.rpc.proto.Base.RespBase getBase() {
      return base_ == null ? com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
    }
    /**
     * <code>.rpc.RespBase base = 255;</code>
     */
    @java.lang.Override
    public com.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder getBaseOrBuilder() {
      return base_ == null ? com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(locale_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, locale_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(result_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, result_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(255, getBase());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(locale_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, locale_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(result_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, result_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBase());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse)) {
        return super.equals(obj);
      }
      com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse other = (com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (!getLocale()
          .equals(other.getLocale())) return false;
      if (!getResult()
          .equals(other.getResult())) return false;
      if (hasBase() != other.hasBase()) return false;
      if (hasBase()) {
        if (!getBase()
            .equals(other.getBase())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + LOCALE_FIELD_NUMBER;
      hash = (53 * hash) + getLocale().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      if (hasBase()) {
        hash = (37 * hash) + BASE_FIELD_NUMBER;
        hash = (53 * hash) + getBase().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.TranslateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.TranslateResponse)
        com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse.class, com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse.Builder.class);
      }

      // Construct using com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getBaseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ = "";
        locale_ = "";
        result_ = "";
        base_ = null;
        if (baseBuilder_ != null) {
          baseBuilder_.dispose();
          baseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.internal_static_rpc_TranslateResponse_descriptor;
      }

      @java.lang.Override
      public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse getDefaultInstanceForType() {
        return com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse build() {
        com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse buildPartial() {
        com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse result = new com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.text_ = text_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.locale_ = locale_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.result_ = result_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.base_ = baseBuilder_ == null
              ? base_
              : baseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse) {
          return mergeFrom((com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse other) {
        if (other == com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLocale().isEmpty()) {
          locale_ = other.locale_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasBase()) {
          mergeBase(other.getBase());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                locale_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                result_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 2042: {
                input.readMessage(
                    getBaseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 2042
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object locale_ = "";
      /**
       * <code>string locale = 2;</code>
       * @return The locale.
       */
      public java.lang.String getLocale() {
        java.lang.Object ref = locale_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          locale_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string locale = 2;</code>
       * @return The bytes for locale.
       */
      public com.google.protobuf.ByteString
          getLocaleBytes() {
        java.lang.Object ref = locale_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locale_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string locale = 2;</code>
       * @param value The locale to set.
       * @return This builder for chaining.
       */
      public Builder setLocale(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        locale_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string locale = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocale() {
        locale_ = getDefaultInstance().getLocale();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string locale = 2;</code>
       * @param value The bytes for locale to set.
       * @return This builder for chaining.
       */
      public Builder setLocaleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        locale_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>string result = 3;</code>
       * @return The result.
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string result = 3;</code>
       * @return The bytes for result.
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string result = 3;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        result_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string result = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        result_ = getDefaultInstance().getResult();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string result = 3;</code>
       * @param value The bytes for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        result_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.github.paopaoyue.mesh.rpc.proto.Base.RespBase base_;
      private com.google.protobuf.SingleFieldBuilder<
          com.github.paopaoyue.mesh.rpc.proto.Base.RespBase, com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder, com.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder> baseBuilder_;
      /**
       * <code>.rpc.RespBase base = 255;</code>
       * @return Whether the base field is set.
       */
      public boolean hasBase() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       * @return The base.
       */
      public com.github.paopaoyue.mesh.rpc.proto.Base.RespBase getBase() {
        if (baseBuilder_ == null) {
          return base_ == null ? com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
        } else {
          return baseBuilder_.getMessage();
        }
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder setBase(com.github.paopaoyue.mesh.rpc.proto.Base.RespBase value) {
        if (baseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          base_ = value;
        } else {
          baseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder setBase(
          com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder builderForValue) {
        if (baseBuilder_ == null) {
          base_ = builderForValue.build();
        } else {
          baseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder mergeBase(com.github.paopaoyue.mesh.rpc.proto.Base.RespBase value) {
        if (baseBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            base_ != null &&
            base_ != com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance()) {
            getBaseBuilder().mergeFrom(value);
          } else {
            base_ = value;
          }
        } else {
          baseBuilder_.mergeFrom(value);
        }
        if (base_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder clearBase() {
        bitField0_ = (bitField0_ & ~0x00000008);
        base_ = null;
        if (baseBuilder_ != null) {
          baseBuilder_.dispose();
          baseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       */
      public com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder getBaseBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getBaseFieldBuilder().getBuilder();
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       */
      public com.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder getBaseOrBuilder() {
        if (baseBuilder_ != null) {
          return baseBuilder_.getMessageOrBuilder();
        } else {
          return base_ == null ?
              com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
        }
      }
      /**
       * <code>.rpc.RespBase base = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.paopaoyue.mesh.rpc.proto.Base.RespBase, com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder, com.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder> 
          getBaseFieldBuilder() {
        if (baseBuilder_ == null) {
          baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.paopaoyue.mesh.rpc.proto.Base.RespBase, com.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder, com.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder>(
                  getBase(),
                  getParentForChildren(),
                  isClean());
          base_ = null;
        }
        return baseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:rpc.TranslateResponse)
    }

    // @@protoc_insertion_point(class_scope:rpc.TranslateResponse)
    private static final com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse();
    }

    public static com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TranslateResponse>
        PARSER = new com.google.protobuf.AbstractParser<TranslateResponse>() {
      @java.lang.Override
      public TranslateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TranslateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TranslateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.paopaoyue.mesh.translate_application.proto.Translate.TranslateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TranslateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_TranslateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TranslateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_TranslateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%translate-application/translate.proto\022" +
      "\003rpc\032\016rpc/base.proto\"0\n\020TranslateRequest" +
      "\022\014\n\004text\030\001 \001(\t\022\016\n\006locale\030\002 \001(\t\"_\n\021Transl" +
      "ateResponse\022\014\n\004text\030\001 \001(\t\022\016\n\006locale\030\002 \001(" +
      "\t\022\016\n\006result\030\003 \001(\t\022\034\n\004base\030\377\001 \001(\0132\r.rpc.R" +
      "espBase*?\n\021ServiceStatusCode\022\016\n\nSERVICE_" +
      "OK\020\000\022\032\n\024LOCALE_NOT_SUPPORTED\020\262\333\0062O\n\021Dict" +
      "ionaryService\022:\n\tTranslate\022\025.rpc.Transla" +
      "teRequest\032\026.rpc.TranslateResponseBB\n5com" +
      ".github.paopaoyue.mesh.translate_applica" +
      "tion.protoB\tTranslateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.paopaoyue.mesh.rpc.proto.Base.getDescriptor(),
        });
    internal_static_rpc_TranslateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_TranslateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_TranslateRequest_descriptor,
        new java.lang.String[] { "Text", "Locale", });
    internal_static_rpc_TranslateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_TranslateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_TranslateResponse_descriptor,
        new java.lang.String[] { "Text", "Locale", "Result", "Base", });
    descriptor.resolveAllFeaturesImmutable();
    com.github.paopaoyue.mesh.rpc.proto.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
