{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mesh-proxy.serviceAccountName" . }}
  labels:
    {{- include "mesh-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}

---

apiVersion: v1
kind: Role
metadata:
  name: {{ include "mesh-proxy.serviceAccountRoleName" . }}
  labels:
    { { - include "mesh-proxy.labels" . | nindent 4 } }
  { { - with .Values.serviceAccount.annotations } }
  annotations:
    { { - toYaml . | nindent 4 } }
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mesh-proxy.serviceAccountRoleBindingName" . }}
  labels:
    { { - include "mesh-proxy.labels" . | nindent 4 } }
  { { - with .Values.serviceAccount.annotations } }
  annotations:
    { { - toYaml . | nindent 4 } }
subjects:
  - kind: ServiceAccount
    name: {{ include "mesh-proxy.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mesh-proxy.serviceAccountRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
