using System.Text;
using System.Text.RegularExpressions;

var argsMap = ParseArgs(args);

if (!argsMap.TryGetValue("service-name", out var serviceName) ||
	!argsMap.TryGetValue("service-alias", out var serviceAlias) ||
	!argsMap.TryGetValue("proto-dir", out var protoDir) ||
	!argsMap.TryGetValue("output-dir", out var outputDir) ||
	!argsMap.TryGetValue("namespace", out var outputNamespace))
{
	Console.Error.WriteLine("Usage: --service-name <name> --service-alias <alias> --proto-dir <path> --output-dir <path> --namespace <ns> [--proto-namespace <ns>] [--test-output-dir <path>] [--test-namespace <ns>] [--config-output-path <path>] (test/config paths have defaults)");
	return 1;
}

var protoNamespace = argsMap.TryGetValue("proto-namespace", out var ns) ? ns : "Rpc";
var serviceAliasPascal = ToPascal(serviceAlias);

var methods = ParseMethods(protoDir);
if (methods.Count == 0)
{
	Console.Error.WriteLine($"No rpc method found under: {protoDir}");
	return 2;
}

Directory.CreateDirectory(outputDir);

var interfaceCode = BuildInterface(outputNamespace, protoNamespace, serviceAliasPascal, methods);
var callerCode = BuildCaller(outputNamespace, protoNamespace, serviceAliasPascal, serviceName, methods);

var interfacePath = Path.Combine(outputDir, $"I{serviceAliasPascal}Caller.cs");
var callerPath = Path.Combine(outputDir, $"{serviceAliasPascal}Caller.cs");

var testOutputDir = argsMap.TryGetValue("test-output-dir", out var testDir) ? testDir : ResolveDefaultTestOutputDir(outputDir);
var testNamespace = argsMap.TryGetValue("test-namespace", out var providedTestNamespace)
	? providedTestNamespace
	: BuildDefaultTestNamespace(outputNamespace);
var configOutputPath = argsMap.TryGetValue("config-output-path", out var configPath) ? configPath : ResolveDefaultConfigOutputPath(outputDir);

await File.WriteAllTextAsync(interfacePath, interfaceCode, Encoding.UTF8);
await File.WriteAllTextAsync(callerPath, callerCode, Encoding.UTF8);

Console.WriteLine($"Generated: {interfacePath}");
Console.WriteLine($"Generated: {callerPath}");

if (!string.IsNullOrWhiteSpace(testOutputDir))
{
	Directory.CreateDirectory(testOutputDir);
	var testPath = Path.Combine(testOutputDir, $"{serviceAliasPascal}CallerTests.cs");
	var testCode = BuildMockTest(testNamespace, outputNamespace, protoNamespace, serviceAliasPascal, methods.First());
	await File.WriteAllTextAsync(testPath, testCode, Encoding.UTF8);
	Console.WriteLine($"Generated: {testPath}");
}

if (!string.IsNullOrWhiteSpace(configOutputPath))
{
	var configDirectory = Path.GetDirectoryName(configOutputPath);
	if (!string.IsNullOrWhiteSpace(configDirectory))
	{
		Directory.CreateDirectory(configDirectory);
	}

	var configCode = BuildConfigTemplate(serviceName);
	await File.WriteAllTextAsync(configOutputPath, configCode, Encoding.UTF8);
	Console.WriteLine($"Generated: {configOutputPath}");
}

return 0;

static Dictionary<string, string> ParseArgs(string[] args)
{
	var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
	for (var i = 0; i < args.Length; i++)
	{
		var arg = args[i];
		if (!arg.StartsWith("--", StringComparison.Ordinal))
		{
			continue;
		}

		var key = arg[2..];
		if (i + 1 >= args.Length)
		{
			continue;
		}

		result[key] = args[i + 1];
		i++;
	}

	return result;
}

static List<ProtoMethod> ParseMethods(string protoDir)
{
	if (!Directory.Exists(protoDir))
	{
		throw new DirectoryNotFoundException($"Proto directory not found: {protoDir}");
	}

	var regex = new Regex(@"rpc\s+([A-Za-z0-9_]+)\s*\(\s*([A-Za-z0-9_\.]+)\s*\)\s*returns\s*\(\s*([A-Za-z0-9_\.]+)\s*\)", RegexOptions.Compiled);
	var methods = new List<ProtoMethod>();

	foreach (var file in Directory.EnumerateFiles(protoDir, "*.proto", SearchOption.TopDirectoryOnly))
	{
		foreach (var line in File.ReadLines(file))
		{
			var match = regex.Match(line);
			if (!match.Success)
			{
				continue;
			}

			var rpcName = match.Groups[1].Value;
			methods.Add(new ProtoMethod(
				RpcMethodName: rpcName,
				HandlerName: LowerFirst(rpcName),
				InputType: ShortType(match.Groups[2].Value),
				OutputType: ShortType(match.Groups[3].Value)));
		}
	}

	return methods;
}

static string BuildInterface(string outputNamespace, string protoNamespace, string serviceAlias, IEnumerable<ProtoMethod> methods)
{
	var sb = new StringBuilder();
	sb.AppendLine("// <auto-generated />");
	sb.AppendLine("#nullable enable");
	sb.AppendLine("using System.Threading;");
	sb.AppendLine("using System.Threading.Tasks;");
	sb.AppendLine();
	sb.AppendLine($"namespace {outputNamespace};");
	sb.AppendLine();
	sb.AppendLine($"public interface I{serviceAlias}Caller");
	sb.AppendLine("{");
	foreach (var method in methods)
	{
		sb.AppendLine($"    Task<{protoNamespace}.{method.OutputType}> {ToPascal(method.RpcMethodName)}Async({protoNamespace}.{method.InputType} request, YppRpc.Client.RpcCallOptions? options = null, CancellationToken cancellationToken = default);");
	}

	sb.AppendLine("}");
	return sb.ToString();
}

static string BuildCaller(string outputNamespace, string protoNamespace, string serviceAlias, string serviceName, IEnumerable<ProtoMethod> methods)
{
	var sb = new StringBuilder();
	sb.AppendLine("// <auto-generated />");
	sb.AppendLine("#nullable enable");
	sb.AppendLine("using System.Threading;");
	sb.AppendLine("using System.Threading.Tasks;");
	sb.AppendLine();
	sb.AppendLine($"namespace {outputNamespace};");
	sb.AppendLine();
	sb.AppendLine($"public sealed class {serviceAlias}Caller : I{serviceAlias}Caller");
	sb.AppendLine("{");
	sb.AppendLine("    private readonly YppRpc.Client.RpcClient _client;");
	sb.AppendLine();
	sb.AppendLine($"    public {serviceAlias}Caller(YppRpc.Client.RpcClient client)");
	sb.AppendLine("    {");
	sb.AppendLine("        _client = client;");
	sb.AppendLine("    }");
	sb.AppendLine();

	foreach (var method in methods)
	{
		sb.AppendLine($"    public Task<{protoNamespace}.{method.OutputType}> {ToPascal(method.RpcMethodName)}Async({protoNamespace}.{method.InputType} request, YppRpc.Client.RpcCallOptions? options = null, CancellationToken cancellationToken = default)");
		sb.AppendLine("    {");
		sb.AppendLine($"        return _client.CallAsync<{protoNamespace}.{method.InputType}, {protoNamespace}.{method.OutputType}>(\"{serviceName}\", \"{method.HandlerName}\", request, isSystemCall: false, callOptions: options, cancellationToken: cancellationToken);");
		sb.AppendLine("    }");
		sb.AppendLine();
	}

	sb.AppendLine("}");
	return sb.ToString();
}

static string BuildMockTest(string testNamespace, string outputNamespace, string protoNamespace, string serviceAlias, ProtoMethod method)
{
	var sb = new StringBuilder();
	var methodName = ToPascal(method.RpcMethodName);
	sb.AppendLine("using System.Threading;");
	sb.AppendLine("using System.Threading.Tasks;");
	sb.AppendLine("using Moq;");
	sb.AppendLine("using Xunit;");
	sb.AppendLine($"using {outputNamespace};");
	sb.AppendLine("using YppRpc.Client;");
	sb.AppendLine();
	sb.AppendLine("#nullable enable");
	sb.AppendLine();
	sb.AppendLine($"namespace {testNamespace};");
	sb.AppendLine();
	sb.AppendLine($"public class {serviceAlias}CallerTests");
	sb.AppendLine("{");
	sb.AppendLine("    [Fact]");
	sb.AppendLine($"    public async Task {methodName}Async_CanBeMockedViaCallerInterface()");
	sb.AppendLine("    {");
	sb.AppendLine($"        var request = new {protoNamespace}.{method.InputType}();");
	sb.AppendLine($"        var expected = new {protoNamespace}.{method.OutputType}();");
	sb.AppendLine($"        var caller = new Mock<I{serviceAlias}Caller>(MockBehavior.Strict);");
	sb.AppendLine();
	sb.AppendLine($"        caller.Setup(x => x.{methodName}Async(");
	sb.AppendLine($"                It.IsAny<{protoNamespace}.{method.InputType}>(),");
	sb.AppendLine("                It.IsAny<RpcCallOptions?>(),");
	sb.AppendLine("                It.IsAny<CancellationToken>()))");
	sb.AppendLine("            .ReturnsAsync(expected);");
	sb.AppendLine();
	sb.AppendLine($"        var response = await caller.Object.{methodName}Async(request);");
	sb.AppendLine();
	sb.AppendLine("        Assert.Same(expected, response);");
	sb.AppendLine("    }");
	sb.AppendLine("}");
	return sb.ToString();
}

static string BuildDefaultTestNamespace(string outputNamespace)
{
	if (outputNamespace.EndsWith(".Generated", StringComparison.Ordinal))
	{
		return outputNamespace[..^".Generated".Length] + ".Tests";
	}

	return outputNamespace + ".Tests";
}

static string ResolveDefaultTestOutputDir(string outputDir)
{
	var projectDir = ResolveProjectDir(outputDir);
	var parent = Directory.GetParent(projectDir)?.FullName;
	if (string.IsNullOrWhiteSpace(parent))
	{
		return Path.Combine(projectDir, "Tests");
	}

	return Path.Combine(parent, Path.GetFileName(projectDir) + ".Tests");
}

static string ResolveDefaultConfigOutputPath(string outputDir)
{
	var projectDir = ResolveProjectDir(outputDir);
	return Path.Combine(projectDir, "appsettings.json");
}

static string ResolveProjectDir(string outputDir)
{
	var fullOutputDir = Path.GetFullPath(outputDir);
	var directoryInfo = new DirectoryInfo(fullOutputDir);
	if (string.Equals(directoryInfo.Name, "Generated", StringComparison.OrdinalIgnoreCase) && directoryInfo.Parent is not null)
	{
		return directoryInfo.Parent.FullName;
	}

	return fullOutputDir;
}

static string BuildConfigTemplate(string serviceName)
{
  return $$"""
{
  "mesh": {
	"rpc": {
	  "env": "local",
	  "clientEnabled": true,
	  "defaultClientService": {
		"name": "{{serviceName}}",
		"host": "127.0.0.1",
		"port": 8080
	  },
	  "clientServices": [
		{
		  "name": "{{serviceName}}",
		  "host": "127.0.0.1",
		  "port": 8080
		}
	  ],
	  "clientShutDownTimeout": 10,
	  "packetMaxSize": 1048576,
	  "keepAliveTimeout": 6,
	  "keepAliveInterval": 2,
	  "keepAliveIdleTimeout": 10,
	  "keepAliveHeartbeatTimeout": 1
	}
  }
}
""";
}

static string LowerFirst(string value)
{
	if (string.IsNullOrEmpty(value))
	{
		return value;
	}

	return char.ToLowerInvariant(value[0]) + value[1..];
}

static string ToPascal(string value)
{
	if (string.IsNullOrEmpty(value))
	{
		return value;
	}

	return char.ToUpperInvariant(value[0]) + value[1..];
}

static string ShortType(string value)
{
	var index = value.LastIndexOf('.');
	return index < 0 ? value : value[(index + 1)..];
}

internal sealed record ProtoMethod(string RpcMethodName, string HandlerName, string InputType, string OutputType);
