// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.0
// source: rpc/base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// should define your own service status code at >= 100000
type StatusCode int32

const (
	StatusCode_OK StatusCode = 0
	// system error
	StatusCode_CLIENT_INTERNAL_ERROR StatusCode = 101
	StatusCode_NETWORK_ERROR         StatusCode = 201
	StatusCode_SERVICE_UNAVAILABLE   StatusCode = 202
	StatusCode_GATEWAY_TIMEOUT       StatusCode = 203
	StatusCode_UNKNOWN_ERROR         StatusCode = 401
	// service error
	StatusCode_INTERNAL_SERVER_ERROR StatusCode = 90001
	StatusCode_INVALID_PARAM_ERROR   StatusCode = 90002
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:     "OK",
		101:   "CLIENT_INTERNAL_ERROR",
		201:   "NETWORK_ERROR",
		202:   "SERVICE_UNAVAILABLE",
		203:   "GATEWAY_TIMEOUT",
		401:   "UNKNOWN_ERROR",
		90001: "INTERNAL_SERVER_ERROR",
		90002: "INVALID_PARAM_ERROR",
	}
	StatusCode_value = map[string]int32{
		"OK":                    0,
		"CLIENT_INTERNAL_ERROR": 101,
		"NETWORK_ERROR":         201,
		"SERVICE_UNAVAILABLE":   202,
		"GATEWAY_TIMEOUT":       203,
		"UNKNOWN_ERROR":         401,
		"INTERNAL_SERVER_ERROR": 90001,
		"INVALID_PARAM_ERROR":   90002,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_base_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_rpc_base_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_rpc_base_proto_rawDescGZIP(), []int{0}
}

// include this in any rpc response
type RespBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RespBase) Reset() {
	*x = RespBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBase) ProtoMessage() {}

func (x *RespBase) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBase.ProtoReflect.Descriptor instead.
func (*RespBase) Descriptor() ([]byte, []int) {
	return file_rpc_base_proto_rawDescGZIP(), []int{0}
}

func (x *RespBase) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespBase) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_base_proto protoreflect.FileDescriptor

var file_rpc_base_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0xbf, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54,
	0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x65, 0x12, 0x12, 0x0a, 0x0d, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0xc9, 0x01, 0x12, 0x18, 0x0a, 0x13, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0xca, 0x01, 0x12,
	0x14, 0x0a, 0x0f, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f,
	0x55, 0x54, 0x10, 0xcb, 0x01, 0x12, 0x12, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x91, 0x03, 0x12, 0x1b, 0x0a, 0x15, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x91, 0xbf, 0x05, 0x12, 0x19, 0x0a, 0x13, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x92, 0xbf,
	0x05, 0x42, 0x3d, 0x0a, 0x22, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x70,
	0x61, 0x6f, 0x70, 0x61, 0x6f, 0x79, 0x75, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x04, 0x42, 0x61, 0x73, 0x65, 0x5a, 0x11, 0x65,
	0x6e, 0x76, 0x6f, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_base_proto_rawDescOnce sync.Once
	file_rpc_base_proto_rawDescData = file_rpc_base_proto_rawDesc
)

func file_rpc_base_proto_rawDescGZIP() []byte {
	file_rpc_base_proto_rawDescOnce.Do(func() {
		file_rpc_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_base_proto_rawDescData)
	})
	return file_rpc_base_proto_rawDescData
}

var file_rpc_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_base_proto_goTypes = []any{
	(StatusCode)(0),  // 0: rpc.StatusCode
	(*RespBase)(nil), // 1: rpc.RespBase
}
var file_rpc_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_base_proto_init() }
func file_rpc_base_proto_init() {
	if File_rpc_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_base_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RespBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_base_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_base_proto_goTypes,
		DependencyIndexes: file_rpc_base_proto_depIdxs,
		EnumInfos:         file_rpc_base_proto_enumTypes,
		MessageInfos:      file_rpc_base_proto_msgTypes,
	}.Build()
	File_rpc_base_proto = out.File
	file_rpc_base_proto_rawDesc = nil
	file_rpc_base_proto_goTypes = nil
	file_rpc_base_proto_depIdxs = nil
}
