/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.paopaoyue.rpc_generator_gradle_plugin;

import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;

class RpcGeneratorPluginPluginTest {

    @TempDir
    File projectDir;

    @Test
    void verifyConfigTask() throws IOException {
        // Set up the test build
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'test'");
        writeString(new File(projectDir, "build.gradle"), "plugins { \n  id 'java' \n  id 'io.github.paopaoyue.ypp-rpc-generator' \n} \ngroup = 'io.github.paopaoyue' \nrpcGenerator { \n  serviceName = 'test' \n  serviceShortAlias = 'test' \n  protoRepoPath = 'idl' \n} \n");

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withProjectDir(projectDir);
        runner.withArguments("verifyConfig");
        runner.build();

    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
