services:

  proxy:

    build:
        context: .
        dockerfile: Dockerfile
        args:
        - ENVOY_CONFIG=local.yaml
    image: ypp-rpc-mesh-proxy:latest
    container_name: proxy
    restart: always
    network_mode: host
    ports:
    - "${PORT_PROXY:-10000}:10000"
