services:

  proxy:

    build:
        context: .
        dockerfile: Dockerfile
        args:
        - ENVOY_CONFIG=envoy-docker.yaml
    image: ypp-rpc-mesh-proxy:latest
    container_name: proxy
    restart: always
    network_mode: host
