apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mesh-proxy.fullname" . }}
  labels:
    {{- include "mesh-proxy.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.service.targetPort }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.golang
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.golang.v3alpha.Config
              is_terminal_filter: true
              library_id: ypp-rpc-go-proxy
              library_path: "/lib/ypp-rpc-go-proxy.so"
              plugin_name: ypp-rpc-go-proxy
              plugin_config:
                "@type": type.googleapis.com/xds.type.v3.TypedStruct
                value:
                  log.level: "{{ .Values.mesh.proxy.logLevel }}"
                  mesh.rpc.PacketMaxSize: {{ .Values.mesh.proxy.PacketMaxSize }}
                  mesh.rpc.KeepAliveTimeout: {{ .Values.mesh.proxy.KeepAliveTimeout }}
                  mesh.rpc.KeepAliveInterval: {{ .Values.mesh.proxy.KeepAliveInterval }}
                  mesh.rpc.KeepAliveIdleTimeout: {{ .Values.mesh.proxy.KeepAliveIdleTimeout }}
                  mesh.rpc.UpstreamMaxResend: {{ .Values.mesh.proxy.UpstreamMaxResend }}
                  mesh.rpc.UpstreamConnectionTimeout: {{ .Values.mesh.proxy.UpstreamConnectionTimeout }}
                  mesh.rpc.BlockListSize: {{ .Values.mesh.proxy.BlockListSize }}
                  mesh.rpc.BlockExpireTime: {{ .Values.mesh.proxy.BlockExpireTime }}
                  mesh.rpc.DiscoveryType: "{{ .Values.mesh.proxy.DiscoveryType }}"
                  mesh.rpc.MetricsType: "{{ .Values.mesh.proxy.MetricsType }}"
                  mesh.rpc.static_services:
    {{ toYaml .Values.mesh.proxy.staticServices | indent 10 }}
                  mesh.rpc.metrics_endpoint:
    {{ toYaml .Values.mesh.proxy.metricsEndpoint | indent 10 }}

      clusters:
      - name: plainText
        type: ORIGINAL_DST
        lb_policy: CLUSTER_PROVIDED