apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mesh-proxy.serviceAccountName" . }}
  labels:
    {{- include "mesh-proxy.labels" . | nindent 6 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mesh-proxy.serviceAccountRoleName" . }}
  labels:
    {{- include "mesh-proxy.labels" . | nindent 6 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "services"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mesh-proxy.serviceAccountRoleBindingName" . }}
  labels:
    {{- include "mesh-proxy.labels" . | nindent 6 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mesh-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "mesh-proxy.serviceAccountRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
