// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc-test/test.proto
// Protobuf Java Version: 4.26.0

package com.github.paopaoyue.mesh.rpc.proto;

public final class RpcTest {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_EchoRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_rpc_EchoRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_EchoResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_rpc_EchoResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 26,
                /* patch= */ 0,
                /* suffix= */ "",
                RpcTest.class.getName());
    }

    static {
        String[] descriptorData = {
                "\n\023rpc-test/test.proto\022\003rpc\032\016rpc/base.pro" +
                        "to\"\033\n\013EchoRequest\022\014\n\004text\030\001 \001(\t\":\n\014EchoR" +
                        "esponse\022\014\n\004text\030\001 \001(\t\022\034\n\004base\030\377\001 \001(\0132\r.r" +
                        "pc.RespBase*#\n\021ServiceStatusCode\022\016\n\nSERV" +
                        "ICE_OK\020\0002@\n\021DictionaryService\022+\n\004echo\022\020." +
                        "rpc.EchoRequest\032\021.rpc.EchoResponseB.\n#co" +
                        "m.github.paopaoyue.mesh.rpc.protoB\007RpcTe" +
                        "stb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                Base.getDescriptor(),
                        });
        internal_static_rpc_EchoRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_rpc_EchoRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_rpc_EchoRequest_descriptor,
                new String[]{"Text",});
        internal_static_rpc_EchoResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_rpc_EchoResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_rpc_EchoResponse_descriptor,
                new String[]{"Text", "Base",});
        descriptor.resolveAllFeaturesImmutable();
        Base.getDescriptor();
    }

    private RpcTest() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    /**
     * Protobuf enum {@code rpc.ServiceStatusCode}
     */
    public enum ServiceStatusCode
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SERVICE_OK = 0;</code>
         */
        SERVICE_OK(0),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>SERVICE_OK = 0;</code>
         */
        public static final int SERVICE_OK_VALUE = 0;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                ServiceStatusCode> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<ServiceStatusCode>() {
                    public ServiceStatusCode findValueByNumber(int number) {
                        return ServiceStatusCode.forNumber(number);
                    }
                };
        private static final ServiceStatusCode[] VALUES = values();

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 26,
                    /* patch= */ 0,
                    /* suffix= */ "",
                    ServiceStatusCode.class.getName());
        }

        private final int value;

        private ServiceStatusCode(int value) {
            this.value = value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static ServiceStatusCode valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static ServiceStatusCode forNumber(int value) {
            switch (value) {
                case 0:
                    return SERVICE_OK;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ServiceStatusCode>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return RpcTest.getDescriptor().getEnumTypes().get(0);
        }

        public static ServiceStatusCode valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:rpc.ServiceStatusCode)
    }
    public interface EchoRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:rpc.EchoRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string text = 1;</code>
         *
         * @return The text.
         */
        String getText();

        /**
         * <code>string text = 1;</code>
         *
         * @return The bytes for text.
         */
        com.google.protobuf.ByteString
        getTextBytes();
    }

    public interface EchoResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:rpc.EchoResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string text = 1;</code>
         *
         * @return The text.
         */
        String getText();

        /**
         * <code>string text = 1;</code>
         *
         * @return The bytes for text.
         */
        com.google.protobuf.ByteString
        getTextBytes();

        /**
         * <code>.rpc.RespBase base = 255;</code>
         *
         * @return Whether the base field is set.
         */
        boolean hasBase();

        /**
         * <code>.rpc.RespBase base = 255;</code>
         *
         * @return The base.
         */
        Base.RespBase getBase();

        /**
         * <code>.rpc.RespBase base = 255;</code>
         */
        Base.RespBaseOrBuilder getBaseOrBuilder();
    }

    /**
     * Protobuf type {@code rpc.EchoRequest}
     */
    public static final class EchoRequest extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:rpc.EchoRequest)
            EchoRequestOrBuilder {
        public static final int TEXT_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:rpc.EchoRequest)
        private static final EchoRequest DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<EchoRequest>
                PARSER = new com.google.protobuf.AbstractParser<EchoRequest>() {
            @Override
            public EchoRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 26,
                    /* patch= */ 0,
                    /* suffix= */ "",
                    EchoRequest.class.getName());
        }

        static {
            DEFAULT_INSTANCE = new EchoRequest();
        }

        @SuppressWarnings("serial")
        private volatile Object text_ = "";
        private byte memoizedIsInitialized = -1;

        // Use EchoRequest.newBuilder() to construct.
        private EchoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private EchoRequest() {
            text_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RpcTest.internal_static_rpc_EchoRequest_descriptor;
        }

        public static EchoRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EchoRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EchoRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EchoRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EchoRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EchoRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EchoRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static EchoRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static EchoRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static EchoRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static EchoRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static EchoRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(EchoRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static EchoRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<EchoRequest> parser() {
            return PARSER;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RpcTest.internal_static_rpc_EchoRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            EchoRequest.class, Builder.class);
        }

        /**
         * <code>string text = 1;</code>
         *
         * @return The text.
         */
        @Override
        public String getText() {
            Object ref = text_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                text_ = s;
                return s;
            }
        }

        /**
         * <code>string text = 1;</code>
         *
         * @return The bytes for text.
         */
        @Override
        public com.google.protobuf.ByteString
        getTextBytes() {
            Object ref = text_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof EchoRequest)) {
                return super.equals(obj);
            }
            EchoRequest other = (EchoRequest) obj;

            if (!getText()
                    .equals(other.getText())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TEXT_FIELD_NUMBER;
            hash = (53 * hash) + getText().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<EchoRequest> getParserForType() {
            return PARSER;
        }

        @Override
        public EchoRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code rpc.EchoRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:rpc.EchoRequest)
                EchoRequestOrBuilder {
            private int bitField0_;
            private Object text_ = "";

            // Construct using com.github.paopaoyue.mesh.rpc.proto.RpcTest.EchoRequest.newBuilder()
            private Builder() {

            }

            private Builder(
                    BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return RpcTest.internal_static_rpc_EchoRequest_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return RpcTest.internal_static_rpc_EchoRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                EchoRequest.class, Builder.class);
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                text_ = "";
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return RpcTest.internal_static_rpc_EchoRequest_descriptor;
            }

            @Override
            public EchoRequest getDefaultInstanceForType() {
                return EchoRequest.getDefaultInstance();
            }

            @Override
            public EchoRequest build() {
                EchoRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public EchoRequest buildPartial() {
                EchoRequest result = new EchoRequest(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(EchoRequest result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.text_ = text_;
                }
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof EchoRequest) {
                    return mergeFrom((EchoRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(EchoRequest other) {
                if (other == EchoRequest.getDefaultInstance()) return this;
                if (!other.getText().isEmpty()) {
                    text_ = other.text_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                text_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>string text = 1;</code>
             *
             * @return The text.
             */
            public String getText() {
                Object ref = text_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string text = 1;</code>
             *
             * @param value The text to set.
             * @return This builder for chaining.
             */
            public Builder setText(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                text_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string text = 1;</code>
             *
             * @return The bytes for text.
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string text = 1;</code>
             *
             * @param value The bytes for text to set.
             * @return This builder for chaining.
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                text_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string text = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearText() {
                text_ = getDefaultInstance().getText();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:rpc.EchoRequest)
        }

    }

    /**
     * Protobuf type {@code rpc.EchoResponse}
     */
    public static final class EchoResponse extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:rpc.EchoResponse)
            EchoResponseOrBuilder {
        public static final int TEXT_FIELD_NUMBER = 1;
        public static final int BASE_FIELD_NUMBER = 255;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:rpc.EchoResponse)
        private static final EchoResponse DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<EchoResponse>
                PARSER = new com.google.protobuf.AbstractParser<EchoResponse>() {
            @Override
            public EchoResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 26,
                    /* patch= */ 0,
                    /* suffix= */ "",
                    EchoResponse.class.getName());
        }

        static {
            DEFAULT_INSTANCE = new EchoResponse();
        }

        private int bitField0_;
        @SuppressWarnings("serial")
        private volatile Object text_ = "";
        private Base.RespBase base_;
        private byte memoizedIsInitialized = -1;

        // Use EchoResponse.newBuilder() to construct.
        private EchoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }
        private EchoResponse() {
            text_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RpcTest.internal_static_rpc_EchoResponse_descriptor;
        }

        public static EchoResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EchoResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EchoResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EchoResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EchoResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static EchoResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static EchoResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static EchoResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static EchoResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static EchoResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static EchoResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static EchoResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(EchoResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static EchoResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<EchoResponse> parser() {
            return PARSER;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RpcTest.internal_static_rpc_EchoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            EchoResponse.class, Builder.class);
        }

        /**
         * <code>string text = 1;</code>
         *
         * @return The text.
         */
        @Override
        public String getText() {
            Object ref = text_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                text_ = s;
                return s;
            }
        }

        /**
         * <code>string text = 1;</code>
         *
         * @return The bytes for text.
         */
        @Override
        public com.google.protobuf.ByteString
        getTextBytes() {
            Object ref = text_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>.rpc.RespBase base = 255;</code>
         *
         * @return Whether the base field is set.
         */
        @Override
        public boolean hasBase() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.rpc.RespBase base = 255;</code>
         *
         * @return The base.
         */
        @Override
        public Base.RespBase getBase() {
            return base_ == null ? Base.RespBase.getDefaultInstance() : base_;
        }

        /**
         * <code>.rpc.RespBase base = 255;</code>
         */
        @Override
        public Base.RespBaseOrBuilder getBaseOrBuilder() {
            return base_ == null ? Base.RespBase.getDefaultInstance() : base_;
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(255, getBase());
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(255, getBase());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof EchoResponse)) {
                return super.equals(obj);
            }
            EchoResponse other = (EchoResponse) obj;

            if (!getText()
                    .equals(other.getText())) return false;
            if (hasBase() != other.hasBase()) return false;
            if (hasBase()) {
                if (!getBase()
                        .equals(other.getBase())) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TEXT_FIELD_NUMBER;
            hash = (53 * hash) + getText().hashCode();
            if (hasBase()) {
                hash = (37 * hash) + BASE_FIELD_NUMBER;
                hash = (53 * hash) + getBase().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<EchoResponse> getParserForType() {
            return PARSER;
        }

        @Override
        public EchoResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code rpc.EchoResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:rpc.EchoResponse)
                EchoResponseOrBuilder {
            private int bitField0_;
            private Object text_ = "";
            private Base.RespBase base_;
            private com.google.protobuf.SingleFieldBuilder<
                    Base.RespBase, Base.RespBase.Builder, Base.RespBaseOrBuilder> baseBuilder_;

            // Construct using com.github.paopaoyue.mesh.rpc.proto.RpcTest.EchoResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return RpcTest.internal_static_rpc_EchoResponse_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return RpcTest.internal_static_rpc_EchoResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                EchoResponse.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage
                        .alwaysUseFieldBuilders) {
                    getBaseFieldBuilder();
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                text_ = "";
                base_ = null;
                if (baseBuilder_ != null) {
                    baseBuilder_.dispose();
                    baseBuilder_ = null;
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return RpcTest.internal_static_rpc_EchoResponse_descriptor;
            }

            @Override
            public EchoResponse getDefaultInstanceForType() {
                return EchoResponse.getDefaultInstance();
            }

            @Override
            public EchoResponse build() {
                EchoResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public EchoResponse buildPartial() {
                EchoResponse result = new EchoResponse(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(EchoResponse result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.text_ = text_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.base_ = baseBuilder_ == null
                            ? base_
                            : baseBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof EchoResponse) {
                    return mergeFrom((EchoResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(EchoResponse other) {
                if (other == EchoResponse.getDefaultInstance()) return this;
                if (!other.getText().isEmpty()) {
                    text_ = other.text_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.hasBase()) {
                    mergeBase(other.getBase());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                text_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 2042: {
                                input.readMessage(
                                        getBaseFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 2042
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>string text = 1;</code>
             *
             * @return The text.
             */
            public String getText() {
                Object ref = text_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string text = 1;</code>
             *
             * @param value The text to set.
             * @return This builder for chaining.
             */
            public Builder setText(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                text_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string text = 1;</code>
             *
             * @return The bytes for text.
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string text = 1;</code>
             *
             * @param value The bytes for text to set.
             * @return This builder for chaining.
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                text_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string text = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearText() {
                text_ = getDefaultInstance().getText();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             *
             * @return Whether the base field is set.
             */
            public boolean hasBase() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             *
             * @return The base.
             */
            public Base.RespBase getBase() {
                if (baseBuilder_ == null) {
                    return base_ == null ? Base.RespBase.getDefaultInstance() : base_;
                } else {
                    return baseBuilder_.getMessage();
                }
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             */
            public Builder setBase(Base.RespBase value) {
                if (baseBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    base_ = value;
                } else {
                    baseBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             */
            public Builder setBase(
                    Base.RespBase.Builder builderForValue) {
                if (baseBuilder_ == null) {
                    base_ = builderForValue.build();
                } else {
                    baseBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             */
            public Builder mergeBase(Base.RespBase value) {
                if (baseBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) != 0) &&
                            base_ != null &&
                            base_ != Base.RespBase.getDefaultInstance()) {
                        getBaseBuilder().mergeFrom(value);
                    } else {
                        base_ = value;
                    }
                } else {
                    baseBuilder_.mergeFrom(value);
                }
                if (base_ != null) {
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             */
            public Builder clearBase() {
                bitField0_ = (bitField0_ & ~0x00000002);
                base_ = null;
                if (baseBuilder_ != null) {
                    baseBuilder_.dispose();
                    baseBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             */
            public Base.RespBase.Builder getBaseBuilder() {
                bitField0_ |= 0x00000002;
                onChanged();
                return getBaseFieldBuilder().getBuilder();
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             */
            public Base.RespBaseOrBuilder getBaseOrBuilder() {
                if (baseBuilder_ != null) {
                    return baseBuilder_.getMessageOrBuilder();
                } else {
                    return base_ == null ?
                            Base.RespBase.getDefaultInstance() : base_;
                }
            }

            /**
             * <code>.rpc.RespBase base = 255;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    Base.RespBase, Base.RespBase.Builder, Base.RespBaseOrBuilder>
            getBaseFieldBuilder() {
                if (baseBuilder_ == null) {
                    baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            Base.RespBase, Base.RespBase.Builder, Base.RespBaseOrBuilder>(
                            getBase(),
                            getParentForChildren(),
                            isClean());
                    base_ = null;
                }
                return baseBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:rpc.EchoResponse)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
