// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc/base.proto

// Protobuf Java Version: 3.25.0
package com.github.paopaoyue.mesh.grpc_test.proto;

public final class Base {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_RespBase_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_rpc_RespBase_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016rpc/base.proto\022\003rpc\")\n\010RespBase\022\014\n\004cod" +
                        "e\030\001 \001(\005\022\017\n\007message\030\002 \001(\t*\277\001\n\nStatusCode\022" +
                        "\006\n\002OK\020\000\022\031\n\025CLIENT_INTERNAL_ERROR\020e\022\022\n\rNE" +
                        "TWORK_ERROR\020\311\001\022\030\n\023SERVICE_UNAVAILABLE\020\312\001" +
                        "\022\024\n\017GATEWAY_TIMEOUT\020\313\001\022\022\n\rUNKNOWN_ERROR\020" +
                        "\221\003\022\033\n\025INTERNAL_SERVER_ERROR\020\221\277\005\022\031\n\023INVAL" +
                        "ID_PARAM_ERROR\020\222\277\005B+\n#com.github.paopaoy" +
                        "ue.mesh.rpc.protoB\004Baseb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_rpc_RespBase_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_rpc_RespBase_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_rpc_RespBase_descriptor,
                new java.lang.String[]{"Code", "Message",});
    }

    private Base() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    /**
     * <pre>
     * should define your own service status code at &gt;= 100000
     * </pre>
     * <p>
     * Protobuf enum {@code rpc.StatusCode}
     */
    public enum StatusCode
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>OK = 0;</code>
         */
        OK(0),
        /**
         * <pre>
         * system error
         * </pre>
         *
         * <code>CLIENT_INTERNAL_ERROR = 101;</code>
         */
        CLIENT_INTERNAL_ERROR(101),
        /**
         * <code>NETWORK_ERROR = 201;</code>
         */
        NETWORK_ERROR(201),
        /**
         * <code>SERVICE_UNAVAILABLE = 202;</code>
         */
        SERVICE_UNAVAILABLE(202),
        /**
         * <code>GATEWAY_TIMEOUT = 203;</code>
         */
        GATEWAY_TIMEOUT(203),
        /**
         * <code>UNKNOWN_ERROR = 401;</code>
         */
        UNKNOWN_ERROR(401),
        /**
         * <pre>
         * service error
         * </pre>
         *
         * <code>INTERNAL_SERVER_ERROR = 90001;</code>
         */
        INTERNAL_SERVER_ERROR(90001),
        /**
         * <code>INVALID_PARAM_ERROR = 90002;</code>
         */
        INVALID_PARAM_ERROR(90002),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>OK = 0;</code>
         */
        public static final int OK_VALUE = 0;
        /**
         * <pre>
         * system error
         * </pre>
         *
         * <code>CLIENT_INTERNAL_ERROR = 101;</code>
         */
        public static final int CLIENT_INTERNAL_ERROR_VALUE = 101;
        /**
         * <code>NETWORK_ERROR = 201;</code>
         */
        public static final int NETWORK_ERROR_VALUE = 201;
        /**
         * <code>SERVICE_UNAVAILABLE = 202;</code>
         */
        public static final int SERVICE_UNAVAILABLE_VALUE = 202;
        /**
         * <code>GATEWAY_TIMEOUT = 203;</code>
         */
        public static final int GATEWAY_TIMEOUT_VALUE = 203;
        /**
         * <code>UNKNOWN_ERROR = 401;</code>
         */
        public static final int UNKNOWN_ERROR_VALUE = 401;
        /**
         * <pre>
         * service error
         * </pre>
         *
         * <code>INTERNAL_SERVER_ERROR = 90001;</code>
         */
        public static final int INTERNAL_SERVER_ERROR_VALUE = 90001;
        /**
         * <code>INVALID_PARAM_ERROR = 90002;</code>
         */
        public static final int INVALID_PARAM_ERROR_VALUE = 90002;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                StatusCode> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
                    public StatusCode findValueByNumber(int number) {
                        return StatusCode.forNumber(number);
                    }
                };
        private static final StatusCode[] VALUES = values();
        private final int value;

        private StatusCode(int value) {
            this.value = value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static StatusCode valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static StatusCode forNumber(int value) {
            switch (value) {
                case 0:
                    return OK;
                case 101:
                    return CLIENT_INTERNAL_ERROR;
                case 201:
                    return NETWORK_ERROR;
                case 202:
                    return SERVICE_UNAVAILABLE;
                case 203:
                    return GATEWAY_TIMEOUT;
                case 401:
                    return UNKNOWN_ERROR;
                case 90001:
                    return INTERNAL_SERVER_ERROR;
                case 90002:
                    return INVALID_PARAM_ERROR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.github.paopaoyue.mesh.grpc_test.proto.Base.getDescriptor().getEnumTypes().get(0);
        }

        public static StatusCode valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:rpc.StatusCode)
    }

    public interface RespBaseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:rpc.RespBase)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 code = 1;</code>
         *
         * @return The code.
         */
        int getCode();

        /**
         * <code>string message = 2;</code>
         *
         * @return The message.
         */
        java.lang.String getMessage();

        /**
         * <code>string message = 2;</code>
         *
         * @return The bytes for message.
         */
        com.google.protobuf.ByteString
        getMessageBytes();
    }

    /**
     * <pre>
     * include this in any rpc response
     * </pre>
     * <p>
     * Protobuf type {@code rpc.RespBase}
     */
    public static final class RespBase extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:rpc.RespBase)
            RespBaseOrBuilder {
        public static final int CODE_FIELD_NUMBER = 1;
        public static final int MESSAGE_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:rpc.RespBase)
        private static final com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<RespBase>
                PARSER = new com.google.protobuf.AbstractParser<RespBase>() {
            @java.lang.Override
            public RespBase parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase();
        }

        private int code_ = 0;
        @SuppressWarnings("serial")
        private volatile java.lang.Object message_ = "";
        private byte memoizedIsInitialized = -1;

        // Use RespBase.newBuilder() to construct.
        private RespBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RespBase() {
            message_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.paopaoyue.mesh.grpc_test.proto.Base.internal_static_rpc_RespBase_descriptor;
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<RespBase> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new RespBase();
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.paopaoyue.mesh.grpc_test.proto.Base.internal_static_rpc_RespBase_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase.class, com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase.Builder.class);
        }

        /**
         * <code>int32 code = 1;</code>
         *
         * @return The code.
         */
        @java.lang.Override
        public int getCode() {
            return code_;
        }

        /**
         * <code>string message = 2;</code>
         *
         * @return The message.
         */
        @java.lang.Override
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>string message = 2;</code>
         *
         * @return The bytes for message.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (code_ != 0) {
                output.writeInt32(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase)) {
                return super.equals(obj);
            }
            com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase other = (com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase) obj;

            if (getCode()
                    != other.getCode()) return false;
            if (!getMessage()
                    .equals(other.getMessage())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RespBase> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * <pre>
         * include this in any rpc response
         * </pre>
         * <p>
         * Protobuf type {@code rpc.RespBase}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:rpc.RespBase)
                com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBaseOrBuilder {
            private int bitField0_;
            private int code_;
            private java.lang.Object message_ = "";

            // Construct using com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.github.paopaoyue.mesh.grpc_test.proto.Base.internal_static_rpc_RespBase_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.github.paopaoyue.mesh.grpc_test.proto.Base.internal_static_rpc_RespBase_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase.class, com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase.Builder.class);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                code_ = 0;
                message_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.github.paopaoyue.mesh.grpc_test.proto.Base.internal_static_rpc_RespBase_descriptor;
            }

            @java.lang.Override
            public com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase getDefaultInstanceForType() {
                return com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase.getDefaultInstance();
            }

            @java.lang.Override
            public com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase build() {
                com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase buildPartial() {
                com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase result = new com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.code_ = code_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.message_ = message_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase) {
                    return mergeFrom((com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase other) {
                if (other == com.github.paopaoyue.mesh.grpc_test.proto.Base.RespBase.getDefaultInstance()) return this;
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                code_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                message_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>int32 code = 1;</code>
             *
             * @return The code.
             */
            @java.lang.Override
            public int getCode() {
                return code_;
            }

            /**
             * <code>int32 code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {

                code_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>int32 code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 2;</code>
             *
             * @return The message.
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string message = 2;</code>
             *
             * @param value The message to set.
             * @return This builder for chaining.
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                message_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 2;</code>
             *
             * @return The bytes for message.
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message = 2;</code>
             *
             * @param value The bytes for message to set.
             * @return This builder for chaining.
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                message_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMessage() {
                message_ = getDefaultInstance().getMessage();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:rpc.RespBase)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
